/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RecipesRouteImport } from './routes/recipes.route'
import { Route as IndexImport } from './routes/index'
import { Route as RecipesIndexImport } from './routes/recipes.index'
import { Route as RecipeRecipeIdImport } from './routes/recipe.$recipeId'

// Create/Update Routes

const RecipesRouteRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RecipesIndexRoute = RecipesIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecipesRouteRoute,
} as any)

const RecipeRecipeIdRoute = RecipeRecipeIdImport.update({
  id: '/recipe/$recipeId',
  path: '/recipe/$recipeId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRoute
    }
    '/recipe/$recipeId': {
      id: '/recipe/$recipeId'
      path: '/recipe/$recipeId'
      fullPath: '/recipe/$recipeId'
      preLoaderRoute: typeof RecipeRecipeIdImport
      parentRoute: typeof rootRoute
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexImport
      parentRoute: typeof RecipesRouteImport
    }
  }
}

// Create and export the route tree

interface RecipesRouteRouteChildren {
  RecipesIndexRoute: typeof RecipesIndexRoute
}

const RecipesRouteRouteChildren: RecipesRouteRouteChildren = {
  RecipesIndexRoute: RecipesIndexRoute,
}

const RecipesRouteRouteWithChildren = RecipesRouteRoute._addFileChildren(
  RecipesRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/recipes': typeof RecipesRouteRouteWithChildren
  '/recipe/$recipeId': typeof RecipeRecipeIdRoute
  '/recipes/': typeof RecipesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/recipe/$recipeId': typeof RecipeRecipeIdRoute
  '/recipes': typeof RecipesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/recipes': typeof RecipesRouteRouteWithChildren
  '/recipe/$recipeId': typeof RecipeRecipeIdRoute
  '/recipes/': typeof RecipesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/recipes' | '/recipe/$recipeId' | '/recipes/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/recipe/$recipeId' | '/recipes'
  id: '__root__' | '/' | '/recipes' | '/recipe/$recipeId' | '/recipes/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecipesRouteRoute: typeof RecipesRouteRouteWithChildren
  RecipeRecipeIdRoute: typeof RecipeRecipeIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecipesRouteRoute: RecipesRouteRouteWithChildren,
  RecipeRecipeIdRoute: RecipeRecipeIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/recipes",
        "/recipe/$recipeId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/recipes": {
      "filePath": "recipes.route.tsx",
      "children": [
        "/recipes/"
      ]
    },
    "/recipe/$recipeId": {
      "filePath": "recipe.$recipeId.tsx"
    },
    "/recipes/": {
      "filePath": "recipes.index.tsx",
      "parent": "/recipes"
    }
  }
}
ROUTE_MANIFEST_END */
